config/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path
from django.urls.conf import include
from .import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('hinata/', include('hinata.urls')),
    path('kikuchi/', include('kikuchi.urls')),
    path('ezura/', include('ezura.urls')),
    path('satou/', include('satou.urls')),
    path('kazuma/', include('kazuma.urls')),

    path('accounts/', include('allauth.urls')),
]

# 開発サーバーでメディア配信できるようにする設定
urlpatterns += static(settings.MEDIA_URL)
document_root=settings.MEDIA_ROOT

ezura/urls.py
from django.urls import path
from . import views

app_name = 'ezura'
urlpattern = [
    
]

hinata/urls.py
from django.urls import path
from . import views

app_name = 'hinata'
urlpattern = [
    
]

kazuma/urls.py
from django.urls import path
from . import views

app_name = 'kazuma'
urlpattern = [
    
]

kikuchi/urls.py
from django.urls import path
from . import views


app_name = 'kikuchi'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    path('blog_list/', views.BlogListView.as_view(), name="blog_list"),
    path('blog_detail/<int:pk>/', views.BlogDetailView.as_view(), name="blog_detail"),
    path('blog_create/', views.BlogCreateView.as_view(), name="blog_create"),
    path('blog_update/<int:pk>/', views.BlogUpdateView.as_view(), name="blog_update"),
    path('blog_delete/<int:pk>/', views.BlogDeleteView.as_view(), name="blog_delete"),
]

satou/urls.py
from django.urls import path
from . import views

app_name = 'satou'
urlpattern = [
    
]

accounts/models.py
#from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
# Create your models here.

    class Meta:
        verbose_name_plural = 'CustomUser'

ezura/models.py
from django.db import models

# Create your models here.

hinata/models.py
from django.db import models

# Create your models here.

kazuma/models.py
from django.db import models

# Create your models here.

kikuchi/models.py
from django.db import models

# Create your models here.

satou/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render

# Create your views here.

ezura/views.py
from django.shortcuts import render

# Create your views here.

hinata/views.py
from django.shortcuts import render

# Create your views here.

kazuma/views.py
from django.shortcuts import render

# Create your views here.

kikuchi/views.py
from django.shortcuts import render
import logging
from django.urls import reverse_lazy
from django.views import generic
from django.contrib import messages
from .forms import InquiryForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Kikuchi
from .forms import InquiryForm, BlogCreateForm

logger = logging.getLogger(__name__)


class IndexView(generic.TemplateView):
    template_name = "index.html"


class InquiryView(generic.FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('kikuchi:inquiry')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'メッセージを送信しました。')
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)


class BlogListView(LoginRequiredMixin, generic.ListView):
    model = Kikuchi
    template_name = 'blog_list.html'
    paginate_by = 2

    def get_queryset(self):
        blogs = Blog.objects.filter(user=self.request.user).order_by('-created_at')
        return blogs

class BlogDetailView(LoginRequiredMixin, generic.DetailView):
    model = Blog
    template_name = 'blog_detail.html'

class BlogCreateView(LoginRequiredMixin, generic.CreateView):
    model = Kikuchi
    template_name = 'blog_create.html'
    form_class = BlogCreateForm
    success_url = reverse_lazy('kikuchi:blog_list')

    def form_valid(self, form):
        diary = form.save(commit=False)
        diary.user = self.request.user
        diary.save()
        messages.success(self.request, '日記を作成しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "日記の作成に失敗しました。")
        return super().form_invalid(form)

class BlogUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Kikuchi
    template_name = 'blog_update.html'
    form_class = BlogCreateForm

    def get_success_url(self):
        return reverse_lazy('kikuchi:blog_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, '日記を更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "日記の更新に失敗しました。")
        return super().form_invalid(form)

class BlogDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Kikuchi
    template_name = 'blog_delete.html'
    success_url = reverse_lazy('kikuchi:blog_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "日記を削除しました。")
        return super().delete(request, *args, **kwargs)

satou/views.py
from django.shortcuts import render

# Create your views here.

satou/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900"
        rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i"
        rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    <!-- My style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    {% block head %}{% endblock %}
</head>

<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <div class="container px-5">
            <a class="navbar-brand" href="#page-top">Start Bootstrap</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span
                    class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">

                <ul class="navbar-nav mr-auto">
                    <li class="nav-item{% block active_inquiry %}{% endblock%}">
                        <a class="nav-link" href="{% url 'satou:inquiry' %}">INQUIRY</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item {% block active_blog_list %}{% endblock %}">
                        <a href="{% url 'satou:blog_list' %}" class="nav-link">BLOG LIST</a>
                    </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'account_logout'%}">Log Out</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'account_login'%}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <!-- Header-->
    {% block header %}{% endblock %}

    {% if messages %}
    <div class="container">
        <div class="row">
            <div class="my-div-style w-100">
                <ul class="messages" style="list-style:none;">
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                        {{ message}}
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    {% endif %}

    <!-- Content -->
    {% block contents %}{% endblock %}

    <!-- Footer-->
    <footer class="py-5 bg-black">
        <div class="container px-5">
            <p class="m-0 text-center text-white small">Copyright &copy; Your Website 2021</p>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>
</body>

</html>

satou/templates/blog_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}ブログ作成{% endblock %}

{% block active_blog_list %}active{% endblock %}


{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">作成</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

satou/templates/blog_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}ブログ削除{% endblock %}

{% block active_blog_list %}active{% endblock %}


{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST">
                {% csrf_token %}
                <p>本当に削除しますか？</p>
                <button class="btn btn-primary　mt-5" type="submit">削除</button>
                <button class="btn btn-secondary mt-5 ml-2"
                    href="{% url 'satou:blog_detail' object.pk %}">キャンセル</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

satou/templates/blog_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}ブログ詳細{% endblock %}

{% block active_blog_list %}active{% endblock %}


{% block contents %}
<div class="container">
    <div class='my-div-style w-100'>
        <div class="row">
            <div class="col-3">
                <strong>タイトル</strong>
            </div>
            <div class="col-9">
                {{ object.title }}
            </div>
        </div>
        <hr>

        <div class="row">
            <div class="col-3">
                <strong>本文</strong>
            </div>
            <div class="col-9">
                {{ object.content|linebreaksbr }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>写真</strong>
            </div>
            <div class="col-3">
                {% if object.photo1 %}
                <img src="{{ object.photo1.url }}" width="200" height="200">
                {% endif %}
            </div>
            <div class="col-3">
                {% if object.photo2 %}
                <img src="{{ object.photo2.url }}" width="200" height="200">
                {% endif %}
            </div>
            <div class="col-3">
                {% if object.photo3 %}
                <img src="{{ object.photo3.url }}" width="200" height="200">
                {% endif %}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>作成日時</strong>
            </div>
            <div class="col-9">
                {{ object.created_at }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>更新日時</strong>
            </div>
            <div class="col-9">
                {{ object.updated_at }}
            </div>
        </div>
        <a href="{% url 'satou:blog_update' object.pk %}" class="btn btn-success mt-5 mb-3">編集</a>
        <a href="{% url 'satou:blog_delete' object.pk %}" class="btn btn-success mt-5 ml-2 mb-3">削除</a>
    </div>
</div>
{% endblock %}

satou/templates/blog_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}ブログ一覧{% endblock %}

{% block active_blog_list %}active{% endblock%}

{% block head %}
<link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <div class="col-lg col-md-10 mx-auto">
                <div class="clearfix">
                    <a class="btn btn-primary" href="{% url 'satou:blog_create' %}">新規作成</a>
                </div>
                {% for satou in blog_list %}
                <div class="post-preview">
                    <a href="{% url 'satou:blog_detail' diary.pk %}">
                        <h2 class="post-title">
                            {{ blog.title }}
                        </h2>
                        <h3 class="post-subtitle">
                            {{ blog.content|truncatechars:20 }}
                        </h3>
                    </a>
                    <p class="post-meta">{{ blog.created_at }}</p>
                </div>
                <hr>
                {% empty %}
                <p>日記があません。</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

satou/templates/blog_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}日記編集|Private Diary{% endblock %}

{% block active_diary_list %}active{% endblock %}


{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">更新</button>
                <button class="btn btn-secondary ml-2" href="{% url 'diary:diary_detail' object.pk %}">キャンセル</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

satou/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Web上にあなた専用の日記ページを保存できます {% endblock %}

{% block header %}
<header class="masthead text-center text-white">
    <div class="masthead-content">
        <div class="container px-5">
            <h1 class="masthead-heading mb-0">Private Diary</h1>
            <h2 class="masthead-subheading mb-0">あなた専用の日記保存サービス</h2>
            <a class="btn btn-primary btn-xl rounded-pill mt-5" href="{% url 'account_login' %}">LOG IN</a>
        </div>
    </div>
    <div class="bg-circle-1 bg-circle"></div>
    <div class="bg-circle-2 bg-circle"></div>
    <div class="bg-circle-3 bg-circle"></div>
    <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block contents %}
<!-- Content section 1-->
<section id="scroll">
    <div class="container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'assets/img/01.jpg' %}"
                        alt="..." /></div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">For those about to rock...</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam
                        sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione
                        voluptatum molestiae adipisci, beatae obcaecati.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Content section 2-->
<section>
    <div class="container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6">
                <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'assets/img/02.jpg' %}"
                        alt="..." /></div>
            </div>
            <div class="col-lg-6">
                <div class="p-5">
                    <h2 class="display-4">We salute you!</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam
                        sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione
                        voluptatum molestiae adipisci, beatae obcaecati.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Content section 3-->
<section>
    <div class="container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6 order-lg-2">
                <div class="p-5"><img class="img-fluid rounded-circle" src="{% static 'assets/img/03.jpg' %}"
                        alt="..." /></div>
            </div>
            <div class="col-lg-6 order-lg-1">
                <div class="p-5">
                    <h2 class="display-4">Let there be rock!</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod aliquid, mollitia odio veniam
                        sit iste esse assumenda amet aperiam exercitationem, ea animi blanditiis recusandae! Ratione
                        voluptatum molestiae adipisci, beatae obcaecati.</p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

satou/templates/inquiry.html
{% extends 'base.html' %}
{% load static %}

{% block title %} お問い合わせ|Private Diary {% endblock %}

{% block active_inquiry %}active{% endblock%}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style">
            <form method="POST">
                {% csrf_token %}

                {{ form.non_field_errors}}

                {% for field in form %}
                <div class="form-group row">
                    <label for="{{ field.id_for_label}}" class="col-sm-4 col-form-label">
                        <strong>{{ field.label_tag }}</strong>
                    </label>
                    <div class="col-sm-8">
                        {{ field }}
                        {{ field.errors }}
                    </div>
                </div>
                {% endfor %}

                <div class="offset-sm-4 col-sm-8">
                    <button class="btn btn-primary" type="submit">送信</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}